baseURL = "https://example.com/"
languageCode = "ja"
title = "Obsidian Hugo"

timezone = "Asia/Tokyo"

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[menu]
  [[menu.main]]
    name = "ドキュメント"
    identifier = "docs"
    url = "/docs/"
    weight = 10
